import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
const id=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
const [home,owner,member,outsider]=[1,2,3,4].map(id);
await db.exec(`create role anon;create role authenticated;create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to authenticated;
create table public.households(id uuid primary key);
create table public.household_members(household_id uuid,user_id uuid,role text);
create table public.reminder_deliveries(status text check(status in ('pending','processing','accepted','failed')));
create function public.is_household_member(h uuid) returns boolean language sql security definer as $$select exists(select 1 from public.household_members where household_id=h and user_id=auth.uid())$$;
insert into households values('${home}');
insert into household_members values('${home}','${owner}','owner'),('${home}','${member}','member');`);
await db.exec(readFileSync(new URL('../supabase/migrations/202609140006_household_features.sql',import.meta.url),'utf8'));
async function as(user){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role authenticated');}
const save=(features,pause=false)=>db.query('select public.set_household_features($1,$2,$3)',[home,features,pause]);
await as(member);await assert.rejects(()=>save({tasks:false}),/owner/);
await as(outsider);await assert.rejects(()=>save({tasks:false}),/owner/);
await as(owner);await save({tasks:false,recipes:true},true);
await assert.rejects(()=>save({tasks:'false'}),/Invalid/);
await assert.rejects(()=>save({settings:false}),/Invalid/);
await as(member);
assert.equal((await db.query('select features from household_feature_preferences')).rows[0].features.tasks,false);
await assert.rejects(()=>db.exec("update household_feature_preferences set features='{}'"),/permission/);
await as(outsider);assert.equal((await db.query('select * from household_feature_preferences')).rows.length,0);
await as(owner);await save({tasks:true},false);
assert.equal((await db.query('select pause_reminders from household_feature_preferences')).rows[0].pause_reminders,false);
await db.close();
console.log('Household feature DB checks passed: owner writes, member reads, household isolation, validation, restoration.');
