// Run against an isolated PostgreSQL-compatible PGlite instance, never production.
// PGLITE_MODULE=/absolute/path/to/@electric-sql/pglite/dist/index.js node tests/rewardbank.db.mjs
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const [h,owner,kid,sibling,outsider,task]=[1,2,3,4,5,6].map(id);
await db.exec(`create role anon; create role authenticated; create schema auth;
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth,public to authenticated;
 create table public.households(id uuid primary key);
 create table public.profiles(id uuid primary key);
 create table public.household_members(household_id uuid,user_id uuid,role text);
 create table public.tasks(id uuid primary key,household_id uuid,assignee_id uuid,assignee_ids uuid[],is_done boolean);
 create function public.is_household_member(h uuid) returns boolean language sql security definer as $$ select exists(select 1 from public.household_members where household_id=h and user_id=auth.uid()) $$;
 insert into households values('${h}');
 insert into profiles values('${owner}'),('${kid}'),('${sibling}'),('${outsider}');
 insert into household_members values('${h}','${owner}','owner'),('${h}','${kid}','member'),('${h}','${sibling}','member');
 insert into tasks values('${task}','${h}','${kid}',array['${kid}'::uuid],false);`);
await db.exec(readFileSync(new URL('../supabase/migrations/202609140004_rewardbank.sql',import.meta.url),'utf8'));
async function as(user){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role authenticated');}
const command=(action,payload={})=>db.query('select public.rewardbank_command($1,$2,$3)',[h,action,payload]);
await as(kid);await assert.rejects(()=>command('enable',{enabled:true}),/owner/);
await as(owner);await command('enable',{enabled:true});await command('enroll',{child_id:kid});await command('enroll',{child_id:sibling});
await command('chore',{child_id:kid,task_id:task,points:10});
const chore=(await db.query('select id from rewardbank_chores')).rows[0].id;
await assert.rejects(()=>command('approve',{id:chore}),/complete/);
await command('reward',{title:'Movie night',kind:'experience',cost:8});
const reward=(await db.query('select id from rewardbank_rewards')).rows[0].id;
await as(kid);await assert.rejects(()=>command('approve',{id:chore}),/Parent/);
await assert.rejects(()=>db.exec('update rewardbank_accounts set balance=999'),/permission/);
assert.equal((await db.query('select * from rewardbank_accounts')).rows.length,1);
await assert.rejects(()=>command('redeem',{reward_id:reward}),/Not enough/);
await db.exec(`reset role;update tasks set is_done=true where id='${task}'`);
await as(owner);await command('approve',{id:chore});await command('approve',{id:chore});
assert.equal((await db.query('select balance from rewardbank_accounts where child_id=$1',[kid])).rows[0].balance,10);
await as(kid);await command('redeem',{reward_id:reward});
assert.equal((await db.query('select balance from rewardbank_accounts')).rows[0].balance,2);
await assert.rejects(()=>command('redeem',{reward_id:reward}),/Not enough/);
const request=(await db.query('select id from rewardbank_redemptions')).rows[0].id;
await as(owner);await command('decline',{id:request});await command('decline',{id:request});
assert.equal((await db.query('select balance from rewardbank_accounts where child_id=$1',[kid])).rows[0].balance,10);
await as(outsider);assert.equal((await db.query('select * from rewardbank_accounts')).rows.length,0);await assert.rejects(()=>command('redeem',{reward_id:reward}),/access/);
await as(owner);await command('enable',{enabled:false});
await as(kid);await assert.rejects(()=>command('redeem',{reward_id:reward}),/paused/);
await db.exec('reset role; create table public.meals(id uuid primary key);');
await db.exec(readFileSync(new URL('../supabase/migrations/202609140005_recipe_book.sql',import.meta.url),'utf8'));
await as(kid);
await db.query('insert into public.household_recipes(household_id,created_by,title,recipe) values($1,$2,$3,$4)',[h,kid,'Pancakes',{ingredients:['1 cup flour'],instructions:['Mix and cook']}]);
await as(sibling);assert.equal((await db.query('select * from household_recipes')).rows.length,1);
await as(outsider);assert.equal((await db.query('select * from household_recipes')).rows.length,0);
await assert.rejects(()=>db.query('insert into household_recipes(household_id,created_by,title,recipe) values($1,$2,$3,$4)',[h,outsider,'Not mine',{}]),/row-level security/);
await as(sibling);
assert.equal((await db.query('delete from household_recipes where household_id=$1 returning id',[h])).rows.length,0);
await as(kid);
assert.equal((await db.query('delete from household_recipes where household_id=$1 returning id',[h])).rows.length,1);
await db.close();
console.log('RewardBank database checks passed: owner authority, household isolation, child privacy, completed-task approval, duplicate approval, overspending, refund idempotency, pause.');
