import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create role anon; create role authenticated;
create table public.tasks(id uuid primary key default gen_random_uuid(), household_id uuid, title text, notes text, assignee_id uuid, assignee_ids uuid[], due_date date, recurrence text, task_type text, list_id uuid, created_by uuid, visibility text, selected_member_ids uuid[], is_done boolean default false);
`);
await db.exec(readFileSync(new URL('../supabase/migrations/202609150001_routine_task_occurrences.sql',import.meta.url),'utf8'));
const id='00000000-0000-0000-0000-000000000001';
await db.query("insert into tasks(id,title,notes,due_date,recurrence) values($1,'Morning','1. Pack lunch','2026-09-18','routine:weekdays')",[id]);
await db.query('update tasks set is_done=true where id=$1',[id]);
let rows=(await db.query('select * from tasks where routine_previous_task_id=$1',[id])).rows;
assert.equal(rows.length,1);assert.equal(rows[0].due_date.toISOString().slice(0,10),'2026-09-21');assert.equal(rows[0].notes,'1. Pack lunch');
await db.query('update tasks set is_done=false where id=$1',[id]);await db.query('update tasks set is_done=true where id=$1',[id]);
assert.equal((await db.query('select * from tasks where routine_previous_task_id=$1',[id])).rows.length,1);
await db.query("update tasks set recurrence='',is_done=true where id=$1",[rows[0].id]);
assert.equal((await db.query('select * from tasks')).rows.length,2);
const monthly=(await db.query("insert into tasks(title,due_date,recurrence) values('Monthly','2026-01-31','routine:monthly') returning id")).rows[0].id;
await db.query('update tasks set is_done=true where id=$1',[monthly]);
assert.equal((await db.query('select due_date from tasks where routine_previous_task_id=$1',[monthly])).rows[0].due_date.toISOString().slice(0,10),'2026-02-28');
console.log('Routine database trigger: weekdays, month-end, stop repeating, duplicate completion passed.');
await db.close();
