import { useEffect, useMemo, useRef, useState } from "react";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { BedDouble, BookOpen, Check, PawPrint, Plus, ShieldCheck, Sparkles, Star, Trophy, X } from "lucide-react";
import { Avatar, Modal, PrimaryButton, TextField } from "../components/ui";
import { useAuth } from "../context/AuthContext";
import { useFamily } from "../context/FamilyContext";
import PageSpotIllustration from "../components/PageSpotIllustration";

const KEY="family-os:rewards:v2";
const seed={balance:1250,chores:[{id:"c1",title:"Clean your room",points:50,icon:"bed",done:false,assigneeId:null},{id:"c2",title:"Feed the dog",points:25,icon:"pet",done:false,assigneeId:null},{id:"c3",title:"Read for 20 mins",points:100,icon:"book",done:false,assigneeId:null}],rewards:[{id:"r1",title:"30m Extra Screen Time",cost:500},{id:"r2",title:"Ice Cream Night",cost:800},{id:"r3",title:"Choose Family Movie",cost:650}],redemptions:[{id:"x1",title:"Later Bedtime",cost:400,status:"fulfilled",when:"2 days ago"}],history:[{id:"h1",title:'Redeemed “Later Bedtime”',when:"2 days ago"}]};
const load=()=>{try{const old=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem("family-os:rewards:v1"));return old?{...seed,...old,redemptions:(old.redemptions||[]).map(item=>({...item,status:item.status||"pending"}))}:seed}catch{return seed}};
const icons={bed:BedDouble,pet:PawPrint,book:BookOpen};

function Milestone({ milestone, onClose }) {
  const root=useRef(null);
  useGSAP(()=>{const media=gsap.matchMedia();media.add("(prefers-reduced-motion: no-preference)",()=>{gsap.fromTo(".milestone-card",{scale:.65,y:24,autoAlpha:0},{scale:1,y:0,autoAlpha:1,duration:.55,ease:"back.out(1.8)"});gsap.fromTo(".milestone-ray",{scale:0,autoAlpha:0},{scale:1,autoAlpha:1,duration:.7,stagger:.04,ease:"back.out(2)"});gsap.fromTo(".milestone-star",{scale:0,rotation:-120},{scale:1,rotation:0,duration:.7,delay:.12,ease:"elastic.out(1,.5)"});});return()=>media.revert();},{scope:root});
  return <div className="milestone-overlay" ref={root} role="dialog" aria-modal="true" aria-label="Milestone reached"><div className="milestone-rays">{Array.from({length:10},(_,i)=><i className="milestone-ray" key={i}/>)}</div><div className="milestone-card"><button onClick={onClose} aria-label="Close"><X/></button><div className="milestone-star"><Trophy/></div><small>Milestone reached</small><h2>{milestone.title}</h2><p>{milestone.detail}</p><PrimaryButton onClick={onClose}>Keep going</PrimaryButton></div></div>;
}

export default function Rewards(){
 const {configured,user,household}=useAuth(); const {members}=useFamily();
 const currentMember=members.find(member=>member.id===user?.id); const realParent=configured?(household?.role==="owner"||currentMember?.role!=="Kid"):true;
 const [previewRole,setPreviewRole]=useState("parent"); const isParent=configured?realParent:previewRole==="parent";
 const [data,setData]=useState(load); const [modal,setModal]=useState(null); const [milestone,setMilestone]=useState(null);
 const defaultAssignee=members.find(member=>member.role==="Kid")?.id||members[0]?.id||"";
 const [chore,setChore]=useState({title:"",points:25,assigneeId:defaultAssignee}); const [reward,setReward]=useState({title:"",cost:500});
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(data)),[data]);
 const visibleChores=data.chores.filter(chore=>!chore.done&&(isParent||!user?.id||!chore.assigneeId||chore.assigneeId===user.id));
 const earned=useMemo(()=>data.chores.filter(c=>c.done).reduce((n,c)=>n+c.points,0),[data.chores]);
 const celebrate=(title,detail)=>setMilestone({title,detail});
 const complete=(id)=>{if(isParent)return;setData(d=>{const item=d.chores.find(c=>c.id===id);if(!item||item.done)return d;const nextBalance=d.balance+item.points;queueMicrotask(()=>celebrate(nextBalance>=1500&&d.balance<1500?"1,500 points!":"Chore complete!",nextBalance>=1500&&d.balance<1500?"You unlocked a new points milestone.":`You earned ${item.points} points.`));return{...d,balance:nextBalance,chores:d.chores.map(c=>c.id===id?{...c,done:true}:c),history:[{id:`h${Date.now()}`,title:`Completed “${item.title}” · +${item.points} points`,when:"Just now"},...d.history]}})};
 const redeem=(item)=>{if(isParent||data.balance<item.cost)return;setData(d=>({...d,redemptions:[{id:`x${Date.now()}`,title:item.title,cost:item.cost,status:"pending",when:"Just now",requestedBy:user?.id||null},...(d.redemptions||[])],history:[{id:`h${Date.now()}`,title:`Requested “${item.title}”`,when:"Just now"},...d.history]}));celebrate("Request sent!","A parent will review your reward request.");};
 const approve=(id)=>setData(d=>{const item=d.redemptions.find(entry=>entry.id===id);if(!item||item.status!=="pending"||d.balance<item.cost)return d;queueMicrotask(()=>celebrate("Reward approved!",`${item.title} is ready to claim.`));return{...d,balance:d.balance-item.cost,redemptions:d.redemptions.map(entry=>entry.id===id?{...entry,status:"approved"}:entry),history:[{id:`h${Date.now()}`,title:`Approved “${item.title}”`,when:"Just now"},...d.history]}});
 const decline=(id)=>setData(d=>({...d,redemptions:d.redemptions.map(item=>item.id===id?{...item,status:"declined"}:item)}));
 const fulfill=(id)=>{setData(d=>({...d,redemptions:d.redemptions.map(item=>item.id===id?{...item,status:"fulfilled"}:item)}));celebrate("Experience complete!","Another happy family memory made.");};
 const addChore=()=>{if(!isParent||!chore.title.trim())return;setData(d=>({...d,chores:[...d.chores,{id:`c${Date.now()}`,title:chore.title.trim(),points:Number(chore.points),assigneeId:chore.assigneeId||null,icon:"bed",done:false}]}));setChore({title:"",points:25,assigneeId:defaultAssignee});setModal(null)};
 const addReward=()=>{if(!isParent||!reward.title.trim())return;setData(d=>({...d,rewards:[...d.rewards,{id:`r${Date.now()}`,title:reward.title.trim(),cost:Number(reward.cost)}]}));setReward({title:"",cost:500});setModal(null)};
 return <div className="rewards-screen pb-28"><header className="rewards-header"><img src="/brand/famos-icon.png" alt="FamOS"/><div><h1>{isParent?"Rewards manager":"My Rewards"}</h1><span>{isParent?"Parent view":"Kid view"}</span></div>{!configured?<button className="role-preview" onClick={()=>setPreviewRole(role=>role==="parent"?"kid":"parent")}>{isParent?<ShieldCheck/>:<Star/>}</button>:<div/>}</header><main className="px-5">
  <section className="balance-card"><div className="reward-balance-spot"><PageSpotIllustration variant="rewards"/></div><p>{isParent?"HOUSEHOLD REWARD BALANCE":"TOTAL BALANCE"}</p><h2>{data.balance.toLocaleString()} <span>Points</span></h2><small>{earned?`${earned} points earned from chores!`:"Start completing chores to earn points"}</small></section>
  {isParent&&<div className="parent-banner"><div><strong>Parent controls</strong><span>Assign chores, set points and approve rewards</span></div><button onClick={()=>setModal("chore")}><Plus/> Chore</button><button onClick={()=>setModal("reward")}><Plus/> Reward</button></div>}
  <div className="rewards-section-title"><h2>{isParent?"Assigned chores":"My chores"}</h2><span>{visibleChores.length} open</span></div><div className="reward-chores">{visibleChores.map(c=>{const Icon=icons[c.icon]||BedDouble;const assignee=members.find(member=>member.id===c.assigneeId);return <article key={c.id}><div className="chore-icon"><Icon/></div><div><strong>{c.title}</strong><span>+{c.points} pts{assignee?` · ${assignee.name}`:""}</span></div>{isParent?(assignee?<Avatar member={assignee}/>:<span className="unassigned">Any kid</span>):<button onClick={()=>complete(c.id)} aria-label={`Complete ${c.title}`}><span/></button>}</article>})}{!visibleChores.length&&<p className="reward-empty">All chores complete. Great work!</p>}</div>
  <div className="rewards-section-title"><h2>{isParent?"Reward catalogue":"Redeem rewards"}</h2><span>{data.rewards.length} experiences</span></div><div className="reward-shop">{data.rewards.map(r=><article key={r.id}><span className="reward-cost">{r.cost} PTS</span><h3>{r.title}</h3><p>Family experience</p><button disabled={isParent||data.balance<r.cost} onClick={()=>redeem(r)}>{isParent?"Kid reward":data.balance<r.cost?"Keep earning":"Request reward"}</button></article>)}</div>
  <div className="rewards-section-title claimed-title"><h2>{isParent?"Redemption approvals":"My requests"}</h2><span>{(data.redemptions||[]).length} total</span></div><div className="claimed-rewards">{(data.redemptions||[]).length?data.redemptions.map(item=><article key={item.id}><div><strong>{item.title}</strong><span>{item.cost} points · {item.when}</span></div>{isParent&&item.status==="pending"?<div className="approval-actions"><button onClick={()=>decline(item.id)} aria-label="Decline"><X/></button><button onClick={()=>approve(item.id)} disabled={data.balance<item.cost}><Check/> Approve</button></div>:isParent&&item.status==="approved"?<button onClick={()=>fulfill(item.id)}>Mark fulfilled</button>:<span className={`redemption-status ${item.status}`}>{item.status}</span>}</article>):<p>No reward requests yet.</p>}</div>
  {data.history[0]&&<div className="reward-history"><Sparkles/><p>{data.history[0].title}<small>{data.history[0].when}.</small></p></div>}
 </main><Modal open={modal==="chore"} onClose={()=>setModal(null)} title="Assign a chore"><TextField label="Chore" value={chore.title} onChange={e=>setChore({...chore,title:e.target.value})}/><TextField label="Points" type="number" min="1" value={chore.points} onChange={e=>setChore({...chore,points:e.target.value})}/><label className="reward-assignee"><span>Assign to</span><select value={chore.assigneeId} onChange={e=>setChore({...chore,assigneeId:e.target.value})}>{members.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><PrimaryButton onClick={addChore}>Assign chore</PrimaryButton></Modal><Modal open={modal==="reward"} onClose={()=>setModal(null)} title="Create an experience"><TextField label="Experience" value={reward.title} onChange={e=>setReward({...reward,title:e.target.value})}/><TextField label="Point cost" type="number" min="1" value={reward.cost} onChange={e=>setReward({...reward,cost:e.target.value})}/><PrimaryButton onClick={addReward}>Create reward</PrimaryButton></Modal>{milestone&&<Milestone milestone={milestone} onClose={()=>setMilestone(null)}/>}</div>
}
