import { useEffect, useMemo, useState } from "react";
import { CalendarPlus, Car, Check, ChevronLeft, FileText, ListPlus, Mic, Repeat2, Sparkles, Trophy, Upload, Users, X } from "lucide-react";
import { useFamily } from "../context/FamilyContext";
import { useCoordination } from "../context/CoordinationContext";

const menu=[
  {id:"capture",label:"Smart capture",copy:"Paste a message or notice",icon:Sparkles},
  {id:"event",label:"Event",copy:"Add a commitment",icon:CalendarPlus},
  {id:"activity",label:"Activity",copy:"Sports, lessons, or clubs",icon:Trophy},
  {id:"ride",label:"Ride request",copy:"Coordinate a pickup or drive",icon:Car},
  {id:"task",label:"Task",copy:"Assign a responsibility",icon:Check},
  {id:"request",label:"Family request",copy:"Ask without chasing",icon:Users},
  {id:"list",label:"List",copy:"Groceries, packing, anything",icon:ListPlus},
  {id:"routine",label:"Routine",copy:"Repeat a household flow",icon:Repeat2},
  {id:"calendar",label:"New calendar",copy:"Group related events",icon:CalendarPlus},
  {id:"taskList",label:"New task list",copy:"Organize reminders",icon:ListPlus},
];
const blank={title:"",description:"",date:new Date().toISOString().slice(0,10),time:"17:00",endTime:"18:00",assigneeId:"",visibility:"household",selectedMemberIds:[],text:"",listType:"custom",recurrenceRule:"Weekly",steps:"",calendarId:"",taskListId:"",eventId:"",activityId:"",activityType:"custom",organization:"",defaultLocation:"",arrivalMinutes:15,color:"#6d4de8"};

function parseCapture(text,members){
  const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);const date=text.match(/\b(20\d{2})-(\d{2})-(\d{2})\b/)?.[0]||new Date().toISOString().slice(0,10);const timeMatch=text.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/i);let capturedTime="09:00";if(timeMatch){let h=Number(timeMatch[1]);if(timeMatch[3].toLowerCase()==="pm"&&h<12)h+=12;if(timeMatch[3].toLowerCase()==="am"&&h===12)h=0;capturedTime=`${String(h).padStart(2,"0")}:${timeMatch[2]||"00"}`;}
  const member=members.find(m=>text.toLowerCase().includes(m.name.toLowerCase()));const title=(lines[0]||"Captured item").replace(/^[-*•]\s*/,"").slice(0,90);
  const deadline=/due|deadline|return|submit|form/i.test(text);return {title,date,time:capturedTime,assigneeId:member?.id||"",confidence:{date:Boolean(text.match(/\b20\d{2}-\d{2}-\d{2}\b/)),assignee:Boolean(member)},suggestions:[{id:"task",kind:"task",title:deadline?title:`Follow up: ${title}`,selected:true},{id:"event",kind:"event",title,selected:/at\s+\d|practice|appointment|meeting|party|trip/i.test(text)}]};
}

export default function UniversalAdd({open,initialType,onClose,onSaved}){
  const {members,events,addTask,addEvent,addGrocery}=useFamily();const {addRequest,addList,addRoutine,calendars,taskLists,activities=[],captureDrafts=[],addCalendar,addTaskList,addActivity,addTransportation,addCaptureDraft,resolveCaptureDraft}=useCoordination();const [type,setType]=useState(initialType||"");const [draft,setDraft]=useState(blank);const [review,setReview]=useState(null);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(open){setType(initialType||"");setDraft({...blank,assigneeId:members[0]?.id||"",calendarId:calendars?.find(c=>c.isDefault)?.id||calendars?.[0]?.id||"",taskListId:taskLists?.find(l=>l.isDefault)?.id||taskLists?.[0]?.id||""});const pending=initialType==="capture"?captureDrafts[0]:null;setReview(pending?{draftId:pending.id,title:pending.sourceName,date:pending.items?.[0]?.date||blank.date,time:pending.items?.[0]?.time||blank.time,assigneeId:"",confidence:{date:pending.confidence==="high",assignee:false},suggestions:(pending.items||[]).map(item=>({...item,selected:item.selected!==false}))}:null);setError("");}},[open,initialType,members,calendars,taskLists,captureDrafts]);
  const title=type==="capture"?(review?"Review detected items":"Smart capture"):menu.find(x=>x.id===type)?.label||"Add to FamOS";
  const canSave=useMemo(()=>type==="capture"?Boolean(review?.suggestions.some(s=>s.selected)):Boolean(draft.title.trim()),[type,draft.title,review]);
  if(!open)return null;
  const save=async()=>{if(!canSave)return;setSaving(true);setError("");try{
    if(type==="task")await addTask({title:draft.title.trim(),assigneeId:draft.assigneeId||null,listId:draft.taskListId||null,due:draft.date,taskType:"family",visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});
    if(type==="event"){const start=new Date(`${draft.date}T${draft.time}`);const end=new Date(`${draft.date}T${draft.endTime}`);await addEvent({title:draft.title.trim(),start:start.toISOString(),end:end>start?end.toISOString():new Date(start.getTime()+3_600_000).toISOString(),location:draft.description,calendarId:draft.calendarId||null,activityId:draft.activityId||null,memberIds:draft.assigneeId?[draft.assigneeId]:[],visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});}
    if(type==="request")await addRequest({title:draft.title.trim(),description:draft.description,responderId:draft.assigneeId||null,deadline:new Date(`${draft.date}T${draft.time}`).toISOString(),visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});
    if(type==="list"){await addList({title:draft.title.trim(),listType:draft.listType,visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});if(draft.listType==="grocery"&&draft.description.trim())for(const name of draft.description.split(/\n|,/).map(x=>x.trim()).filter(Boolean))await addGrocery({name,category:"Other"});}
    if(type==="routine")await addRoutine({title:draft.title.trim(),recurrenceRule:draft.recurrenceRule,steps:draft.steps.split(/\n/).map(x=>x.trim()).filter(Boolean),visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});
    if(type==="activity")await addActivity({name:draft.title.trim(),activityType:draft.activityType,participantIds:draft.assigneeId?[draft.assigneeId]:[],organization:draft.organization,defaultLocation:draft.defaultLocation,arrivalMinutes:Number(draft.arrivalMinutes)||15,primaryDriverId:draft.assigneeId||null,weatherSensitive:true,color:draft.color,visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});
    if(type==="ride"){const event=events.find(e=>e.id===draft.eventId);await addTransportation({eventId:draft.eventId||null,activityId:draft.activityId||event?.activityId||null,driverId:draft.assigneeId||null,passengerIds:[],pickupLocation:draft.description||"Home",destination:event?.location||activities.find(a=>a.id===draft.activityId)?.defaultLocation||"",leaveAt:new Date(`${draft.date}T${draft.time}`).toISOString(),visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});}
    if(type==="calendar")await addCalendar({name:draft.title.trim(),color:draft.color,visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});
    if(type==="taskList")await addTaskList({name:draft.title.trim(),color:draft.color,icon:"list",visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});
    if(type==="capture"){for(const s of review.suggestions.filter(x=>x.selected)){if(s.kind==="task")await addTask({title:s.title,assigneeId:review.assigneeId||null,due:review.date,taskType:"family",visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});else{const start=new Date(`${review.date}T${review.time}`);await addEvent({title:s.title,start:start.toISOString(),end:new Date(start.getTime()+3_600_000).toISOString(),location:"",memberIds:review.assigneeId?[review.assigneeId]:[],visibility:draft.visibility,selectedMemberIds:draft.selectedMemberIds});}}if(review.draftId)await resolveCaptureDraft(review.draftId,"approved");}
    onSaved?.();onClose();
  }catch(e){setError(e.message||"Could not save this item.");}finally{setSaving(false);}};
  return <div className="co-overlay co-add-overlay" role="dialog" aria-modal="true" aria-label={title}><button className="co-scrim" onClick={onClose}/><div className="co-add-sheet"><header>{type&&<button onClick={()=>review?setReview(null):setType("")} aria-label="Back"><ChevronLeft/></button>}<div><span>{review?"Nothing saves without your approval":"Intentional sharing"}</span><h2>{title}</h2></div><button onClick={onClose} aria-label="Close"><X/></button></header>
    {!type?<div className="co-add-menu">{menu.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setType(item.id)}><span><Icon/></span><div><strong>{item.label}</strong><small>{item.copy}</small></div></button>})}<div className="co-upload-row"><button onClick={()=>setType("capture")}><Upload/> Upload screenshot or PDF</button><button onClick={()=>setType("capture")}><Mic/> Speak a request</button></div></div>:
    type==="capture"&&!review?<div className="co-form"><label><span>Paste text from a notice</span><textarea rows="7" value={draft.text} onChange={e=>setDraft({...draft,text:e.target.value})} placeholder={'Example: “School field trip on 2026-10-18 at 8:30 am. Permission form due Friday.”'}/></label><label className="co-file-zone"><FileText/><div><strong>Text file or exported notice</strong><small>Read locally, then review every detected action before saving.</small></div><span className="co-file-button">Choose file</span><input type="file" accept=".txt,.md,text/plain" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const text=await file.text();setDraft({...draft,text});}}/></label><button className="co-primary co-wide" disabled={!draft.text.trim()} onClick={async()=>{const parsed=parseCapture(draft.text,members);const saved=await addCaptureDraft({sourceName:"Quick capture",sourceType:"text",items:parsed.suggestions.map(s=>({...s,date:parsed.date,time:parsed.time})),confidence:parsed.confidence.date?"high":"needs_review"});setReview({...parsed,draftId:saved.id});}}><Sparkles/> Detect items for review</button></div>:
    type==="capture"&&review?<div className="co-review"><div className="co-review-source"><span>FamOS detected</span><strong>{review.title}</strong><small>Check the highlighted fields before saving.</small></div><div className="co-form co-review-fields"><label className={!review.confidence.date?"uncertain":""}><span>Date {!review.confidence.date&&<em>Check this</em>}</span><input type="date" value={review.date} onChange={e=>setReview({...review,date:e.target.value,confidence:{...review.confidence,date:true}})}/></label><label><span>Time</span><input type="time" value={review.time} onChange={e=>setReview({...review,time:e.target.value})}/></label><label className={!review.confidence.assignee?"uncertain":""}><span>Suggested person {!review.confidence.assignee&&<em>Not certain</em>}</span><select value={review.assigneeId} onChange={e=>setReview({...review,assigneeId:e.target.value,confidence:{...review.confidence,assignee:true}})}><option value="">Unassigned</option>{members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label></div><h3>Prepared actions</h3>{review.suggestions.map(s=><label className="co-suggestion" key={s.id}><input type="checkbox" checked={s.selected} onChange={()=>setReview({...review,suggestions:review.suggestions.map(x=>x.id===s.id?{...x,selected:!x.selected}:x)})}/><span><strong>{s.kind==="event"?"Calendar event":"Task"}</strong><small>{s.title}</small></span></label>)}<PrivacyFields draft={draft} setDraft={setDraft} members={members}/></div>:
    <div className="co-form"><label><span>Title</span><input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder={type==="request"?"What do you need help with?":type==="routine"?"School morning":type==="calendar"?"Kids activities":type==="taskList"?"Weekend errands":"Name this item"}/></label>{["event","request","task"].includes(type)&&<><div className="co-form-row"><label><span>Date</span><input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label>{type!=="task"&&<label><span>Time</span><input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label>}</div>{type==="event"&&<label><span>Calendar</span><select value={draft.calendarId} onChange={e=>setDraft({...draft,calendarId:e.target.value})}>{calendars?.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>}{type==="task"&&<label><span>List</span><select value={draft.taskListId} onChange={e=>setDraft({...draft,taskListId:e.target.value})}>{taskLists?.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select></label>}<label><span>{type==="request"?"Suggested responder":"Assign to"}</span><select value={draft.assigneeId} onChange={e=>setDraft({...draft,assigneeId:e.target.value})}><option value="">Unassigned</option>{members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label></>}{type==="event"&&<label><span>Location or note</span><input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>}{type==="list"&&<><label><span>List type</span><select value={draft.listType} onChange={e=>setDraft({...draft,listType:e.target.value})}><option value="custom">Custom</option><option value="grocery">Grocery</option><option value="packing">Packing</option><option value="chores">Chores</option><option value="school">School supplies</option></select></label><label><span>Starting items (optional)</span><textarea rows="4" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="One item per line"/></label></>}{type==="routine"&&<><label><span>Repeats</span><input value={draft.recurrenceRule} onChange={e=>setDraft({...draft,recurrenceRule:e.target.value})}/></label><label><span>Steps</span><textarea rows="5" value={draft.steps} onChange={e=>setDraft({...draft,steps:e.target.value})} placeholder="One step per line"/></label></>}{["calendar","taskList"].includes(type)&&<label><span>Colour</span><input type="color" value={draft.color} onChange={e=>setDraft({...draft,color:e.target.value})}/></label>}<PrivacyFields draft={draft} setDraft={setDraft} members={members}/></div>}
    {error&&<p className="co-form-error">{error}</p>}{type&&!(type==="capture"&&!review)&&<footer><div><small>{type==="capture"?"Only the checked drafts will be saved.":"You can change this later."}</small><strong>{draft.visibility==="private"?"Visible only to you":draft.visibility==="guardian_only"?"Guardians only":draft.visibility==="selected"?"Selected people":"Shared with the household"}</strong></div><button className="co-primary" disabled={!canSave||saving} onClick={save}>{saving?"Saving…":type==="capture"?"Approve and save":"Save"}</button></footer>}
  </div></div>;
}

function PrivacyFields({draft,setDraft,members}){return <fieldset className="co-privacy-fields"><legend>Who can see this?</legend><div>{[["household","Household"],["selected","Selected people"],["private","Only me"],["guardian_only","Guardians only"]].map(([id,label])=><label key={id} className={draft.visibility===id?"active":""}><input type="radio" name="visibility" value={id} checked={draft.visibility===id} onChange={()=>setDraft({...draft,visibility:id})}/><span><i><Check/></i>{label}</span></label>)}</div>{draft.visibility==="selected"&&<div className="co-selected-members">{members.map(m=><label key={m.id}><input type="checkbox" checked={draft.selectedMemberIds.includes(m.id)} onChange={()=>setDraft({...draft,selectedMemberIds:draft.selectedMemberIds.includes(m.id)?draft.selectedMemberIds.filter(id=>id!==m.id):[...draft.selectedMemberIds,m.id]})}/>{m.name}</label>)}</div>}</fieldset>}
