#!/bin/bash
set -euo pipefail

# Normalizes Tauri's generated Xcode project for FamOS App Store archives.
# Run this after `tauri ios init` and whenever the generated project changes.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APPLE_DIR="$ROOT_DIR/src-tauri/gen/apple"
PROJECT_SPEC="$APPLE_DIR/project.yml"
XCODE_PROJECT="$APPLE_DIR/famos.xcodeproj/project.pbxproj"
INFO_PLIST="$APPLE_DIR/famos_iOS/Info.plist"
EXPORT_PLIST="$APPLE_DIR/ExportOptions.plist"
PRIVACY_MANIFEST="$ROOT_DIR/src-tauri/PrivacyInfo.xcprivacy"
TEAM_ID="ZRDVT9WBN4"
BUNDLE_ID="app.fam-os.famos"
BUILD_NUMBER="${APP_BUILD_NUMBER:-1}"

if [[ ! -f "$PROJECT_SPEC" ]]; then
  echo "Generating the Tauri iOS project..."
  cd "$ROOT_DIR"
  npx tauri ios init
fi

# project.yml is generated by Tauri and intentionally ignored by git. Apply
# deterministic release settings before regenerating the .xcodeproj.
perl -0pi -e 's/bundleIdPrefix: .*$/bundleIdPrefix: app.fam-os/m' "$PROJECT_SPEC"
perl -0pi -e 's/(deploymentTarget:\n\s+iOS:) .*?\n/$1 15.0\n/' "$PROJECT_SPEC"
perl -0pi -e 's/PRODUCT_BUNDLE_IDENTIFIER: .*$/PRODUCT_BUNDLE_IDENTIFIER: app.fam-os.famos/m' "$PROJECT_SPEC"
perl -0pi -e 's/CFBundleShortVersionString: .*$/CFBundleShortVersionString: 1.0.0/m' "$PROJECT_SPEC"
perl -0pi -e "s/CFBundleVersion: .*\$/CFBundleVersion: \"$BUILD_NUMBER\"/m" "$PROJECT_SPEC"

if ! grep -q 'CFBundleURLTypes:' "$PROJECT_SPEC"; then
  perl -0pi -e 's/(        CFBundleVersion: .*\n)/$1        CFBundleURLTypes:\n          - CFBundleURLName: app.fam-os.famos\n            CFBundleURLSchemes: [famos]\n/' "$PROJECT_SPEC"
fi

if ! grep -q 'DEVELOPMENT_TEAM:' "$PROJECT_SPEC"; then
  perl -0pi -e 's/(PRODUCT_BUNDLE_IDENTIFIER: app\.fam-os\.famos\n)/$1      DEVELOPMENT_TEAM: ZRDVT9WBN4\n/' "$PROJECT_SPEC"
fi
if ! grep -q 'CODE_SIGN_STYLE:' "$PROJECT_SPEC"; then
  perl -0pi -e 's/(VALID_ARCHS: arm64\s*\n)/$1        CODE_SIGN_STYLE: Automatic\n/' "$PROJECT_SPEC"
fi

# Tauri already adds the root privacy manifest as a resource through
# bundle.resources. Remove an older generated copy so Xcode has one producer
# for PrivacyInfo.xcprivacy instead of two competing copy phases.
if [[ -f "$APPLE_DIR/famos_iOS/PrivacyInfo.xcprivacy" ]]; then
  rm "$APPLE_DIR/famos_iOS/PrivacyInfo.xcprivacy"
fi
if [[ -f "$APPLE_DIR/assets/PrivacyInfo.xcprivacy" ]]; then
  rm "$APPLE_DIR/assets/PrivacyInfo.xcprivacy"
fi

/usr/libexec/PlistBuddy -c 'Set :CFBundleShortVersionString 1.0.0' "$INFO_PLIST"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$INFO_PLIST"
/usr/libexec/PlistBuddy -c 'Set :ITSAppUsesNonExemptEncryption false' "$INFO_PLIST" 2>/dev/null || \
  /usr/libexec/PlistBuddy -c 'Add :ITSAppUsesNonExemptEncryption bool false' "$INFO_PLIST"

plutil -create xml1 "$EXPORT_PLIST"
plutil -insert destination -string export "$EXPORT_PLIST"
plutil -insert method -string app-store-connect "$EXPORT_PLIST"
plutil -insert signingStyle -string automatic "$EXPORT_PLIST"
plutil -insert teamID -string "$TEAM_ID" "$EXPORT_PLIST"

cd "$APPLE_DIR"
xcodegen generate --spec project.yml

# Recent XcodeGen versions may infer the Rust static library under Externals as
# both a link dependency and an app resource. It must be linked, but Apple
# rejects an archive when the standalone libapp.a is also copied into the app.
perl -0pi -e 's/^\s*[A-F0-9]+ \/\* libapp\.a in Resources \*\/ = \{isa = PBXBuildFile; fileRef = [A-F0-9]+ \/\* libapp\.a \*\/; \};\n//m' "$XCODE_PROJECT"
perl -0pi -e 's/^\s*[A-F0-9]+ \/\* libapp\.a in Resources \*\/,\n//m' "$XCODE_PROJECT"

echo "Prepared iOS App Store project:"
echo "  Bundle ID: $BUNDLE_ID"
echo "  Team ID:   $TEAM_ID"
echo "  Version:   1.0.0 ($BUILD_NUMBER)"
