-- Rich operator analytics, revenue ledger, and guarded account deletion.
create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  household_id uuid references public.households(id) on delete set null,
  event_type text not null check (event_type in (
    'invoice_paid', 'payment_failed', 'refund', 'subscription_started',
    'subscription_changed', 'subscription_canceled'
  )),
  amount_cents integer not null default 0,
  currency text not null default 'CAD',
  provider text not null default 'manual',
  external_event_id text unique,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists billing_events_occurred_idx
  on public.billing_events (occurred_at desc);
create index if not exists billing_events_household_idx
  on public.billing_events (household_id, occurred_at desc);

alter table public.billing_events enable row level security;
revoke all on public.billing_events from public, anon, authenticated;

create or replace function public.admin_analytics_snapshot(range_days integer default 90)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  bounded_days integer := greatest(7, least(coalesce(range_days, 90), 730));
  result jsonb;
begin
  if not public.is_famos_admin() then raise exception 'Admin access required'; end if;

  select jsonb_build_object(
    'rangeDays', bounded_days,
    'activeHouseholds7d', (
      select count(distinct household_id) from (
        select household_id from public.tasks where created_at >= now() - interval '7 days'
        union all select household_id from public.messages where created_at >= now() - interval '7 days'
        union all select household_id from public.events where created_at >= now() - interval '7 days'
        union all select household_id from public.grocery_items where created_at >= now() - interval '7 days'
        union all select household_id from public.meals where created_at >= now() - interval '7 days'
      ) activity
    ),
    'activeHouseholds30d', (
      select count(distinct household_id) from (
        select household_id from public.tasks where created_at >= now() - interval '30 days'
        union all select household_id from public.messages where created_at >= now() - interval '30 days'
        union all select household_id from public.events where created_at >= now() - interval '30 days'
        union all select household_id from public.grocery_items where created_at >= now() - interval '30 days'
        union all select household_id from public.meals where created_at >= now() - interval '30 days'
      ) activity
    ),
    'taskCompletionRate', (
      select coalesce(round(100.0 * count(*) filter (where is_done) / nullif(count(*), 0), 1), 0)
      from public.tasks where created_at >= now() - make_interval(days => bounded_days)
    ),
    'revenueCollectedCents', (
      select coalesce(sum(case when event_type = 'refund' then -abs(amount_cents)
                               when event_type = 'invoice_paid' then amount_cents else 0 end), 0)
      from public.billing_events where occurred_at >= now() - make_interval(days => bounded_days)
    ),
    'failedPayments', (
      select count(*) from public.billing_events
      where event_type = 'payment_failed' and occurred_at >= now() - make_interval(days => bounded_days)
    ),
    'adoption', jsonb_build_object(
      'tasks', (select count(distinct household_id) from public.tasks),
      'chat', (select count(distinct household_id) from public.messages),
      'calendar', (select count(distinct household_id) from public.events),
      'groceries', (select count(distinct household_id) from public.grocery_items),
      'meals', (select count(distinct household_id) from public.meals)
    ),
    'series', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'period', to_char(bucket, 'YYYY-MM-DD'),
        'label', to_char(bucket, 'Mon DD'),
        'tasks', (select count(*) from public.tasks where created_at >= bucket and created_at < bucket + interval '1 day'),
        'chats', (select count(*) from public.messages where created_at >= bucket and created_at < bucket + interval '1 day'),
        'events', (select count(*) from public.events where created_at >= bucket and created_at < bucket + interval '1 day'),
        'groceries', (select count(*) from public.grocery_items where created_at >= bucket and created_at < bucket + interval '1 day'),
        'meals', (select count(*) from public.meals where created_at >= bucket and created_at < bucket + interval '1 day'),
        'newFamilies', (select count(*) from public.households where created_at >= bucket and created_at < bucket + interval '1 day'),
        'newUsers', (select count(*) from auth.users where created_at >= bucket and created_at < bucket + interval '1 day'),
        'revenueCents', (select coalesce(sum(case when event_type = 'refund' then -abs(amount_cents)
          when event_type = 'invoice_paid' then amount_cents else 0 end), 0)
          from public.billing_events where occurred_at >= bucket and occurred_at < bucket + interval '1 day')
      ) order by bucket), '[]'::jsonb)
      from generate_series(
        date_trunc('day', now()) - make_interval(days => bounded_days - 1),
        date_trunc('day', now()),
        interval '1 day'
      ) bucket
    ),
    'plans', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'plan', plan_key, 'status', status, 'accounts', accounts,
        'mrrCents', mrr_cents
      ) order by accounts desc), '[]'::jsonb)
      from (
        select plan_key, status, count(*) accounts,
          sum(case when status = 'active' then
            case when billing_interval = 'year' then amount_cents / 12.0 else amount_cents end
          else 0 end)::integer mrr_cents
        from public.account_subscriptions group by plan_key, status
      ) plans
    ),
    'topFamilies', (
      select coalesce(jsonb_agg(to_jsonb(top_family) order by top_family.activity_count desc), '[]'::jsonb)
      from (
        select h.id, h.name,
          coalesce(s.plan_key, 'none') plan,
          coalesce(s.status, 'none') subscription_status,
          coalesce(case when s.status = 'active' then
            case when s.billing_interval = 'year' then s.amount_cents / 12.0 else s.amount_cents end
          else 0 end, 0)::integer mrr_cents,
          ((select count(*) from public.tasks where household_id = h.id and created_at >= now() - make_interval(days => bounded_days)) +
           (select count(*) from public.messages where household_id = h.id and created_at >= now() - make_interval(days => bounded_days)) +
           (select count(*) from public.events where household_id = h.id and created_at >= now() - make_interval(days => bounded_days)) +
           (select count(*) from public.grocery_items where household_id = h.id and created_at >= now() - make_interval(days => bounded_days)) +
           (select count(*) from public.meals where household_id = h.id and created_at >= now() - make_interval(days => bounded_days))) activity_count
        from public.households h
        left join public.account_subscriptions s on s.household_id = h.id
        order by activity_count desc limit 8
      ) top_family
    )
  ) into result;
  return result;
end;
$$;

create or replace function public.admin_list_users(search_text text default '', page_limit integer default 200, page_offset integer default 0)
returns table (
  user_id uuid, email text, display_name text, created_at timestamptz, last_sign_in_at timestamptz,
  household_id uuid, household_name text, member_role text, is_admin boolean,
  task_count bigint, message_count bigint, event_count bigint, grocery_count bigint, meal_count bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select u.id, coalesce(u.email, ''), coalesce(p.display_name, ''), u.created_at, u.last_sign_in_at,
    hm.household_id, h.name, hm.role::text,
    exists(select 1 from public.admin_users au where au.user_id = u.id and au.is_active),
    (select count(*) from public.tasks t where t.assignee_id = u.id),
    (select count(*) from public.messages m where m.sender_id = u.id),
    (select count(*) from public.events e where e.created_by = u.id),
    (select count(*) from public.grocery_items g where g.added_by = u.id),
    (select count(*) from public.meals ml where ml.created_by = u.id)
  from auth.users u
  left join public.profiles p on p.id = u.id
  left join public.household_members hm on hm.user_id = u.id
  left join public.households h on h.id = hm.household_id
  where public.is_famos_admin()
    and (coalesce(trim(search_text), '') = '' or
      coalesce(u.email, '') ilike '%' || trim(search_text) || '%' or
      coalesce(p.display_name, '') ilike '%' || trim(search_text) || '%' or
      coalesce(h.name, '') ilike '%' || trim(search_text) || '%')
  order by u.created_at desc
  limit greatest(1, least(coalesce(page_limit, 200), 500))
  offset greatest(coalesce(page_offset, 0), 0);
$$;

create or replace function public.admin_record_billing_event(
  target_household uuid, next_event_type text, next_amount_cents integer,
  next_currency text default 'CAD', event_note text default ''
) returns bigint
language plpgsql security definer set search_path = '' as $$
declare new_id bigint;
begin
  if not public.is_famos_admin() then raise exception 'Admin access required'; end if;
  if next_event_type not in ('invoice_paid','payment_failed','refund','subscription_started','subscription_changed','subscription_canceled')
    then raise exception 'Invalid billing event'; end if;
  insert into public.billing_events(household_id, event_type, amount_cents, currency, metadata)
  values(target_household, next_event_type, coalesce(next_amount_cents, 0), upper(coalesce(next_currency, 'CAD')),
    jsonb_build_object('note', coalesce(event_note, ''))) returning id into new_id;
  perform public.admin_log('record_billing_event', 'household', target_household::text,
    jsonb_build_object('eventType', next_event_type, 'amountCents', next_amount_cents));
  return new_id;
end;
$$;

create or replace function public.admin_delete_user(target_user uuid, confirmation text)
returns void language plpgsql security definer set search_path = '' as $$
declare target_email text; target_role public.household_role; target_household uuid;
begin
  if not public.is_famos_admin() then raise exception 'Admin access required'; end if;
  if target_user = auth.uid() then raise exception 'You cannot delete your active admin identity'; end if;
  if exists(select 1 from public.admin_users where user_id = target_user) then
    raise exception 'Admin identities cannot be deleted from user management';
  end if;
  select email into target_email from auth.users where id = target_user;
  if target_email is null then raise exception 'User not found'; end if;
  if confirmation <> target_email then raise exception 'Type the full email address to confirm deletion'; end if;
  select household_id, role into target_household, target_role
    from public.household_members where user_id = target_user limit 1;
  if target_role = 'owner' then raise exception 'Delete the family account to delete its owner'; end if;

  perform public.admin_log('delete_user', 'user', target_user::text,
    jsonb_build_object('email', target_email, 'householdId', target_household));
  delete from public.household_invitations where invited_by = target_user;
  delete from public.tasks where created_by = target_user;
  delete from public.grocery_items where added_by = target_user;
  delete from public.events where created_by = target_user;
  delete from public.expenses where created_by = target_user;
  update public.meals set cook_ids = array_remove(cook_ids, target_user),
    created_by = case when created_by = target_user then null else created_by end
    where target_user = any(cook_ids) or created_by = target_user;
  delete from auth.users where id = target_user;
end;
$$;

create or replace function public.admin_delete_household(target_household uuid, confirmation text)
returns void language plpgsql security definer set search_path = '' as $$
declare target_name text; member_ids uuid[];
begin
  if not public.is_famos_admin() then raise exception 'Admin access required'; end if;
  select name into target_name from public.households where id = target_household;
  if target_name is null then raise exception 'Family account not found'; end if;
  if confirmation <> target_name then raise exception 'Type the exact family name to confirm deletion'; end if;
  select coalesce(array_agg(user_id), '{}'::uuid[]) into member_ids
    from public.household_members where household_id = target_household;
  if exists(select 1 from public.admin_users where user_id = any(member_ids)) then
    raise exception 'This family contains an administrator identity and cannot be deleted';
  end if;

  perform public.admin_log('delete_household', 'household', target_household::text,
    jsonb_build_object('name', target_name, 'memberCount', cardinality(member_ids)));
  delete from public.households where id = target_household;
  delete from auth.users u where u.id = any(member_ids)
    and not exists(select 1 from public.household_members hm where hm.user_id = u.id)
    and not exists(select 1 from public.admin_users au where au.user_id = u.id);
end;
$$;

grant execute on function public.admin_analytics_snapshot(integer) to authenticated;
grant execute on function public.admin_list_users(text, integer, integer) to authenticated;
grant execute on function public.admin_record_billing_event(uuid, text, integer, text, text) to authenticated;
grant execute on function public.admin_delete_user(uuid, text) to authenticated;
grant execute on function public.admin_delete_household(uuid, text) to authenticated;
notify pgrst, 'reload schema';
